### ISSUE TITLE
bot-tokenのtypeを増やしたい

### ISSUE THREAD

**Issue by Crab55e** [Crab55e/MetsChat#16]
config,tomlの
```toml
[discord.bot-token]
type = "..."
```
が現在システム環境変数かベタ書きの2種しかない
多分人によってはもっと別の方法が欲しいだろうから、そこらへん考えるべきかもしれない
